name: Unit and integration tests

on:
  push:
    branches: [ "main", "docker" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-22.04

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: BACKEND/package-lock.json
    - name: Install dependencies
      working-directory: ./BACKEND
      run: npm install
    - name: Start Docker services
      working-directory: ./BACKEND
      run: docker compose -f docker-compose.dev.yml up -d
    - name: Wait for services
      run: sleep 5
    - name: Run unit tests
      working-directory: ./BACKEND
      run: npm run unit-test
    - name: Run integration tests
      working-directory: ./BACKEND
      run: npm run integration-test